/**
 * Created by Administrator on 2017/6/27.
 */
// 请求全部版本管理里列表
export const REQUEST_VERSIONMAINPAGE = 'VERSIONDATA/MAIN/REQUEST_VERSIONMAINPAGE';
//更新列表
export const UPDATA_VERSIONMAINPAGE = 'VERSIONDATA/MAIN/UPDATA_VERSIONMAINPAGE';
//缓存版本号名称
export const SET_VERSIONNAME = 'VERSIONDATA/MAIN/SET_VERSIONNAME';

//发送获取当前版本号title属性的请求
export const REQUEST_VERSIONTITLE = 'VERSIONDATA/MAIN/REQUEST_VERSIONTITLE';
//缓存版本号详情表格title属性
export const GET_VERSIONTITLE = 'VERSIONDATA/MAIN/GET_VERSIONTITLE';

//请求版本号详情表格数据
export const REQUEST_VERSIONCHECKPAGE = 'VERSIONDATA/MAIN/REQUEST_VERSIONCHECKPAGE';
//获取版本号详细内容
export const GET_VERSIONCHECKPAGE = 'VERSIONDATA/MAIN/GET_VERSIONCHECKPAGE';
//存储添加条件
export const GET_FILTERCONDTION = 'VERSIONDATA/MAIN/GET_FILTERCONDTION';
//版本管理index页面的查询的条件值
export const VERSION_DATA = 'VERSIONDATA/MAIN/VERSION_DATA';
//版本管理index页面的查询请求
export const SEARCH_VERSION = 'VERSIONDATA/MAIN/SEARCH_VERSION';

// 缓存可显示的列
export const SET_SHOWCOLUMNS = 'VERSIONDATA/MAIN/SET_SHOWCOLUMNS';
// 显示所有的列
export const SHOW_ALLCOLUMNS = 'VERSIONDATA/MAIN/SHOW_ALLCOLUMNS';
//缓存显示隐藏筛选条件数据
export const SHOW_FILTERCONDITION = 'VERSIONDATA/MAIN/SHOW_FILTERCONDITION';
// 缓存当前编辑的条件
export const SET_CONDITIONDATA = 'VERSIONDATA/MAIN/SET_CONDITIONDATA';
// 缓存条件list
export const SET_CONDITIONLIST ='VERSIONDATA/MAIN/SET_CONDITIONLIST';
//FILTER_VERSIONDATA
export const FILTER_VERSIONDATA = 'VERSIONDATA/MAIN/FILTER_VERSIONDATA';













