/**
 * 点击登陆按钮
 * @type {string}
 */
// 请求数据子集list
export const REQUEST_DOMAINSERVICELIST = 'MASTERDATA/SERVICE/REQUEST_DOMAINSERVICELIST';

//数据子集 基本数据
export const DOMAIN_LIST_DATA = 'MASTERDATA/SERVICE/DOMAIN_LIST_DATA';
// 请求模型list
export const REQUEST_MODEL_LIST = 'MASTERDATA/SERVICE/REQUEST_MODEL_LIST';
// 请求实体list
export const REQUEST_ENTITY_LIST = 'MASTERDATA/SERVICE/REQUEST_ENTITY_LIST';
// 请求实体表list
export const REQUEST_TABLE_DATA_LIST = 'MASTERDATA/SERVICE/REQUEST_TABLE_DATA_LIST';
// 请求任务list
export const REQUEST_TASK_LIST = 'MASTERDATA/SERVICE/REQUEST_TASK_LIST';

export const UPDATE_DOMAINSERVICELIST = 'MASTERDATA/SERVICE/UPDATE_DOMAINSERVICELIST';
export const MODEL_LIST_DATA = 'MASTERDATA/SERVICE/MODEL_LIST_DATA';
export const ENTITY_LIST_DATA = 'MASTERDATA/SERVICE/ENTITY_LIST_DATA';
export const TASK_LIST_DATA = 'MASTERDATA/SERVICE/TASK_LIST_DATA';
export const TABLE_LIST_DATA = 'MASTERDATA/SERVICE/TABLE_LIST_DATA';

// 缓存图元中的数据
export const CACHE_CURRENT_FLOW_DATA = 'MASTERDATA/SERVICE/CACHE_CURRENT_FLOW_DATA';
//流 字段数据
export const CONCAT_FLOW_FIELD_DATA = 'MASTERDATA/SERVICE/CONCAT_FLOW_FIELD_DATA';
//保存编排后的数据
export const SAVE_ARRANGE_SERVICE = 'MASTERDATA/SERVICE/SAVE_ARRANGE_SERVICE';
//改变服务状态
export const CHANGE_SERVICE_STATUS = 'MASTERDATA/SERVICE/CHANGE_SERVICE_STATUS';
//删除服务状态
export const REMOVE_SERVICE_STATUS = 'MASTERDATA/SERVICE/REMOVE_SERVICE_STATUS';
//添加共享任务
export const ADD_SHARE_SERVICE = 'MASTERDATA/SERVICE/ADD_SHARE_SERVICE';
//修改共享任务
export const UPDATE_SHARE_SERVICE = 'MASTERDATA/SERVICE/UPDATE_SHARE_SERVICE';
//任务输出scheam
export const TASK_OUTPUT_SCHEMA = 'MASTERDATA/SERVICE/TASK_OUTPUT_SCHEMA';
//请求任务流出schema
export const REQUEST_TASK_OUTPUT_SCHEMA = 'MASTERDATA/SERVICE/REQUEST_TASK_OUTPUT_SCHEMA';
//请求用户列表
export const REQUEST_USRE_LIST = 'MASTERDATA/SERVICE/REQUEST_USRE_LIST';
//存放用户列表
export const USER_LIST = 'MASTERDATA/SERVICE/USER_LIST';
//编排后的数据流
export const TASK_EDIT_FLOW = 'MASTERDATA/SERVICE/TASK_EDIT_FLOW';
//拿到编排后的数据流
export const GET_TASK_EDIT_FLOW = 'MASTERDATA/SERVICE/GET_TASK_EDIT_FLOW';
//拿到编排后的数据流
export const UPDATE_TASKARRAYLIST = 'MASTERDATA/SERVICE/UPDATE_TASKARRAYLIST';
//添加ws
export const ADD_WS = 'MASTERDATA/SERVICE/ADD_WS';
//修改ws
export const UPDATE_WS = 'MASTERDATA/SERVICE/UPDATE_WS';
//获取一个服务的详细信息
export const REQUEST_WS_DETAIL = 'MASTERDATA/SERVICE/REQUEST_WS_DETAIL';
//存放一个服务的详细信息
export const WS_DETAIL = 'MASTERDATA/SERVICE/WS_DETAIL';
//请求共享日志
export const REQUEST_SHARE_LOG = 'MASTERDATA/SERVICE/REQUEST_SHARE_LOG';
//删除共享日志
export const CLEAR_SHARE_LOG = 'MASTERDATA/SERVICE/CLEAR_SHARE_LOG';
//存储共享日志
export const SHARE_LOG_LIST = 'MASTERDATA/SERVICE/SHARE_LOG_LIST';
//请求ws列表
export const REQUEST_WS_LIST = 'MASTERDATA/SERVICE/REQUEST_WS_LIST';
//修改ws 状态
export const CHANGE_WS_STATUS = 'MASTERDATA/SERVICE/CHANGE_WS_STATUS';
//删除 ws
export const DELETE_WS = 'MASTERDATA/SERVICE/DELETE_WS';
//存储ws列表
export const WS_LIST = 'MASTERDATA/SERVICE/WS_LIST';
//请求ws 日志列表
export const REQUEST_SERVICE_LOG_LIST = 'MASTERDATA/SERVICE/REQUEST_SERVICE_LOG_LIST';
//删除ws 日志列表
export const CLEAR_SERVICE_LOG = 'MASTERDATA/SERVICE/CLEAR_SERVICE_LOG';
//存储ws 日志列表
export const WS_LOG_LIST = 'MASTERDATA/SERVICE/WS_LOG_LIST';
//
export const OPENENTITYFIELDSHAREWIN = 'MASTERDATA/SERVICE/OPENENTITYFIELDSHAREWIN';
export const CLOSEENTITYFIELDSHAREWIN = 'MASTERDATA/SERVICE/CLOSEENTITYFIELDSHAREWIN';
// 增加数据
export const SAVE_DOMAINSERVICEDATA = 'MASTERDATA/SERVICE/ADD_DOMAINSERVICEDATA';
// 请求测试服务的接口参数
export const REQUEST_TEST_PARAMS = 'MASTERDATA/SERVICE/REQUEST_TEST_PARAMS';
// 存放测试服务的接口参数
export const WS_TEST_PARAMS = 'MASTERDATA/SERVICE/WS_TEST_PARAMS';
// 开始测试服务
export const BEGIN_TEST_WS = 'MASTERDATA/SERVICE/BEGIN_TEST_WS';
// 测试结果
export const TEST_WS_RESULT = 'MASTERDATA/SERVICE/TEST_WS_RESULT';
//请求共享管理数据
export const SHARE_DATA = 'MASTERDATA/SERVICE/SHARE_DATA';
//请求共享管理数据(结果)
export const SHARE_LIST_DATA = 'MASTERDATA/SERVICE/SHARE_LIST_DATA';
//条件筛选
export const SHOW_CONDITION='MASTERDATA/SERVICE/SHOW_CONDITION';
export const SHARE_SET_CONDITIONDATA='MASTERDATA/SERVICE/SHARE_SET_CONDITIONDATA';
export const SHARE_SET_CONDITIONLIST='MASTERDATA/SERVICE/SHARE_SET_CONDITIONLIST';
export const SHARE_SHOW_ALLCOLUMNS='MASTERDATA/SERVICE/SHARE_SHOW_ALLCOLUMNS';
export const SHARE_SET_SHOWCOLUMNS='MASTERDATA/SERVICE/SHARE_SET_SHOWCOLUMNS';


















