export const SENDING_REQUEST = 'MASTER/LOGIN/SENDING_REQUEST';
export const LOGIN_ERROR = 'MASTER/LOGIN/LOGIN_ERROR';
export const LOGIN_SUCCESS = 'MASTER/LOGIN/LOGIN_SUCCESS';
export const CHANGE_LOGIN_STATUS = 'MASTER/LOGIN/CHANGE_LOGIN_STATUS';
