/**
 * 点击登陆按钮
 * @type {string}
 */
//发送请求
export const REQUEST_DOMAINDATA = 'MASTERDATA/DESIGNPAGE/REQUEST_DOMAINDATA';
// 请求回来的数据子集数据
export const UPDATE_DOMAINDATA = 'MASTERDATA/DESIGNPAGE/UPDATE_DOMAINDATA';
// 显示错误信息
export const SHOW_ERROR = 'MASTERDATA/DESIGNPAGE/SHOW_ERROR';
// 显示数据子集编辑弹出框
export const SHOW_DOMAINCREATE = 'MASTERDATA/DESIGNPAGE/SHOW_DOMAINCREATE';
// 增加数据子集属性信息
export const ADD_DOMAINATTR = 'MASTERDATA/DESIGNPAGE/ADD_DOMAINATTR';
// 在输入框中输入或者更改模型名称后
export const CHANGE_MODELNAME = 'MASTERDATA/DESIGNPAGE/CHANGE_MODELNAME';
// 保存数据子集
export const SAVE_DOMAIN = 'MASTERDATA/DESIGNPAGE/SAVE_DOMAIN';
// delete数据子集
export const DELETE_DOMAIN = 'MASTERDATA/DESIGNPAGE/DELETE_DOMAIN';
// 导出数据子集
export const EXPORT_DOMAIN = 'MASTERDATA/DESIGNPAGE/EXPORT_DOMAIN';
// 修改数据子集
export const UPDATE_DOMAIN = 'MASTERDATA/DESIGNPAGE/UPDATE_DOMAIN';
// 缓存model的属性
export const SET_MODELATTR = 'MASTERDATA/DESIGNPAGE/SET_MODELATTR';
// 点击model请求model下的实体
export const CLICK_MODEL = 'MASTERDATA/DESIGNPAGE/CLICK_MODEL';
// 更新state的entityData数据
export const UPDATE_ENTITYDATA = 'MASTERDATA/DESIGNPAGE/UPDATE_ENTITYDATA';
// 显示实体编辑弹窗
export const SHOW_ENTITYMODAL = 'MASTERDATA/DESIGNPAGE/SHOW_ENTITYMODAL';
// 保存实体
export const SAVE_ENTITY = 'MASTERDATA/DESIGNPAGE/SAVE_ENTITY';
// 在输入框中输入或者更改实体名称后
export const CHANGE_ENTITYNAME = 'MASTERDATA/DESIGNPAGE/CHANGE_ENTITYNAME';
// 在输入框中输入或者更改实体描述后
export const CHANGE_ENTITYDESC = 'MASTERDATA/DESIGNPAGE/CHANGE_ENTITYDESC';
// 添加当前数据子集的属性信息
export const ADD_ENTITY = 'MASTERDATA/DESIGNPAGE/ADD_ENTITY';
// 删除实体
export const DELETE_ENTITY = 'MASTERDATA/DESIGNPAGE/DELETE_ENTITY';
// 切换实体可用或不可用
export const CHANGE_STATUS = 'MASTERDATA/DESIGNPAGE/CHANGE_STATUS';
// 显示属性编辑弹出框
export const SHOW_ATTRCREATE = 'MASTERDATA/DESIGNPAGE/SHOW_ATTRCREATE';
// 点击实体列表中的属性链接时，缓存实体数据
export const SET_CLICKENTITYDATA = 'MASTERDATA/DESIGNPAGE/SET_CLICKENTITYDATA';
// 点击实体列表中的属性链接请求属性列表
export const REQUEST_ATTRDATA = 'MASTERDATA/DESIGNPAGE/REQUEST_ATTRDATA';
// 缓存请求出来的属性列表
export const UPDATE_ATTRLIST = 'MASTERDATA/DESIGNPAGE/UPDATE_ATTRLIST';
// 缓存当前的属性信息
export const SET_ATTRIBUTEDATA = 'MASTERDATA/DESIGNPAGE/SET_ATTRIBUTEDATA';
// 保存属性
export const SAVE_ATTRIBUTE = 'MASTERDATA/DESIGNPAGE/SAVE_ATTRIBUTE';
// 删除属性
export const DELETE_ATTR = 'MASTERDATA/DESIGNPAGE/DELETE_ATTR';
// 请求所有的model
export const REQUEST_ALLMODELS = 'MASTERDATA/DESIGNPAGE/REQUEST_ALLMODELS';
// 缓存所有的modelList数据
export const SET_ALLMODELLIST = 'MASTERDATA/DESIGNPAGE/SET_ALLMODELLIST';
// 下拉框中选中模型后，请求该模型下的所有实体
export const SELECT_THISMODEL = 'MASTERDATA/DESIGNPAGE/SELECT_THISMODEL';
// 下拉框中选中模型后，将请求出的实体list绑定在实体下拉框上
export const SET_SELECTEDMODELS_ENTITY = 'MASTERDATA/DESIGNPAGE/SET_SELECTEDMODELS_ENTITY';
// 下拉框中选中实体后，请求该模型下的所有属性
export const SELECT_THISENTITY = 'MASTERDATA/DESIGNPAGE/SELECT_THISENTITY';
// 下拉框中选中实体后，将请求出的属性list绑定在属性下拉框上
export const SET_SELECTEDENTITYS_ATTR = 'MASTERDATA/DESIGNPAGE/SET_SELECTEDENTITYS_ATTR';
// 请求该实体的历史版本
export const REQUEST_ALLVERSION = 'MASTERDATA/DESIGNPAGE/REQUEST_ALLVERSION';
// 更新版本list缓存
export const UPDATE_VERSIONLIST = 'MASTERDATA/DESIGNPAGE/UPDATE_VERSIONLIST';
// 搜索数据子集
export const SEARCH_DOMAINDATA = 'MASTERDATA/DESIGNPAGE/SEARCH_DOMAINDATA';
//数据子集编辑的标记
export const DOMAIN_EDTIOR_SIGN = 'MASTERDATA/DESIGNPAGE/DOMAIN_EDTIOR_SIGN';
//查看是否有变动数据(请求)
export const MONITOR = 'MASTERDATA/DESIGNPAGE/MONITOR';
//查看是否有变动数据(结果)
export const SET_MONITOR = 'MASTERDATA/DESIGNPAGE/SET_MONITOR';
//请求监控变动的数据
export const REQUEST_MONITOR_LIST = 'MASTERDATA/DESIGNPAGE/REQUEST_MONITOR_LIST';
//请求监控变动的数据(结果)
export const SET_MONITOR_LIST = 'MASTERDATA/DESIGNPAGE/SET_MONITOR_LIST';
//请求同步
export const REQUEST_SYNCH = 'MASTERDATA/DESIGNPAGE/REQUEST_SYNCH';
//请求查看变动字段
export const REQUEST_CHECK = 'MASTERDATA/DESIGNPAGE/REQUEST_CHECK';
//变动字段数据
export const MONITOR_DATA_LIST = 'MASTERDATA/DESIGNPAGE/MONITOR_DATA_LIST';



















