/**
 * 点击登陆按钮
 * @type {string}
 */
// 请求数据子集list
export const REQUEST_DOMAINDATA = 'MASTERDATA/MAIN/REQUEST_DOMAINDATA';
// 请求回来的数据子集数据list
export const UPDATE_DOMAINDATA = 'MASTERDATA/MAIN/UPDATE_DOMAINDATA';
// 缓存数据子集
export const SET_DOMAINATTR = 'MASTERDATA/MAIN/SET_DOMAINATTR';
// 导出数据子集内模型结构
export const EXPORT_DOMAIN = 'MASTERDATA/MAIN/EXPORT_DOMAIN';
// 缓存模型
export const SET_MODELATTR = 'MASTERDATA/MAIN/SET_MODELATTR';
// 请求实体list
export const REQUEST_ENTITYLIST = 'MASTERDATA/MAIN/REQUEST_ENTITYLIST';
// 缓存实体list
export const UPDATE_ENTITYLIST = 'MASTERDATA/MAIN/UPDATE_ENTITYLIST';
// 缓存实体
export const SET_ENTITYATTR = 'MASTERDATA/MAIN/SET_ENTITYATTR';
// 请求实体list
export const REQUEST_ATTRLIST = 'MASTERDATA/MAIN/REQUEST_ATTRLIST';
// 请求实体基本属性list
export const REQUEST_BASE_ATTRLIST = 'MASTERDATA/MAIN/REQUEST_BASE_ATTRLIST';
// 存储实体基本属性list
export const ENTITY_BASE_ATTRLIST = 'MASTERDATA/MAIN/ENTITY_BASE_ATTRLIST';
// 缓存属性list
export const UPDATE_ATTRLIST = 'MASTERDATA/MAIN/UPDATE_ATTRLIST';
// 请求实体数据list
export const REQUEST_ENTITYDATALIST = 'MASTERDATA/MAIN/REQUEST_ENTITYDATALIST';
// 缓存实体数据list
export const UPDATE_ENTITYDATALIST = 'MASTERDATA/MAIN/UPDATE_ENTITYDATALIST';
// 显示高级筛选
export const SHOW_FILTERCONDITION = 'MASTERDATA/MAIN/SHOW_FILTERCONDITION';
// 缓存当前编辑的条件
export const SET_CONDITIONDATA = 'MASTERDATA/MAIN/SET_CONDITIONDATA';
// 缓存条件list
export const SET_CONDITIONLIST = 'MASTERDATA/MAIN/SET_CONDITIONLIST';
// 提交条件进行筛选
export const FILTER_ENTITYDATA = 'MASTERDATA/MAIN/FILTER_ENTITYDATA';
// 缓存可显示的列
export const SET_SHOWCOLUMNS = 'MASTERDATA/MAIN/SET_SHOWCOLUMNS';
// 显示所有的列
export const SHOW_ALLCOLUMNS = 'MASTERDATA/MAIN/SHOW_ALLCOLUMNS';
// 是否显示发布版本的form
export const SHOW_ADDVERSION = 'MASTERDATA/MAIN/SHOW_ADDVERSION';
// 缓存要发布的版本数据
export const SET_VERSIONDATA = 'MASTERDATA/MAIN/SET_VERSIONDATA';
// 向后台发送保存版本的请求
export const SAVE_VERSION = 'MASTERDATA/MAIN/SAVE_VERSION';
// 每次新建modal时，设置一个key
export const SET_MODALKEY = 'MASTERDATA/MAIN/SET_MODALKEY';
// 请求实体的历史版本
export const REQUEST_ALLVERSIONS = 'MASTERDATA/MAIN/REQUEST_ALLVERSIONS';
// 缓存实体的历史版本
export const SET_ENTITYVERSIONLIST = 'MASTERDATA/MAIN/SET_ENTITYVERSIONLIST';
// 缓存请求实体数据的类型 “Data”:数据量    "gatherData" : 变动数据
export const SET_ENTITYDATATYPE = 'MASTERDATA/MAIN/SET_ENTITYDATATYPE';
// 请求实体的待审批数据
export const REQUEST_ENTITYGATHERDATA = 'MASTERDATA/MAIN/REQUEST_ENTITYGATHERDATA';
// set数据审计记录模态框的显示状态
export const SET_AUDITDATAMODALSTATUS = 'MASTERDATA/MAIN/SET_AUDITDATAMODALSTATUS';
// 请求数据审计记录的值
export const REQUEST_DATAAUDITRECORD = 'MASTERDATA/MAIN/REQUEST_DATAAUDITRECORD';
// 缓存数据审计记录的值
export const UPDATE_DATAAUDITRECORD = 'MASTERDATA/MAIN/UPDATE_DATAAUDITRECORD';
// 导出数据审计记录
export const EXPORT_AUDITDATARECORD = 'MASTERDATA/MAIN/EXPORT_AUDITDATARECORD';
// 过滤数据审计数据
export const FILTER_ENTITYAUDITDATA = 'MASTERDATA/MAIN/FILTER_ENTITYAUDITDATA';
// 改变实体的是否启用的状态
export const CHANGE_STATUS = 'MASTERDATA/MAIN/CHANGE_STATUS';
//versionPage 选择的版本的标示id
export const VERSION_ID = 'MASTERDATA/MAIN/VERSION_ID';
//versionDataPage 请求对应版本的数据
export const REQUEST_DATA = 'MASTERDATA/MAIN/REQUEST_DATA';
//刷新版本的数据
export const UPDATE_VERSIONDATALIST = 'MASTERDATA/MAIN/UPDATE_VERSIONDATALIST';
//请求版本的属性
export const REQUEST_VERSIONATTRLIST = 'MASTERDATA/MAIN/REQUEST_VERSIONATTRLIST';
//刷新版本的属性
export const UPDATE_VERSIONATTRLIST = 'MASTERDATA/MAIN/UPDATE_VERSIONATTRLIST';
//获得版本的名字
export const GET_NAME = 'MASTERDATA/MAIN/GET_NAME';
//FILTER_VERSIONDATA
export const FILTER_VERSIONDATA = 'MASTERDATA/MAIN/FILTER_VERSIONDATA';

// 请求实体的任务list
export const REQUEST_ENTITYTASK = 'MASTERDATA/MAIN/REQUEST_ENTITYTASK';
// 缓存实体的任务list
export const UPDATE_ENTITYTASKLIST = 'MASTERDATA/MAIN/UPDATE_ENTITYTASKLIST';
// 缓存任务的属性信息
export const SET_TASKATTR = 'MASTERDATA/MAIN/SET_TASKATTR';
// 请求数据源list
export const REQ_DATASOURCELIST = 'MASTERDATA/MAIN/REQ_DATASOURCELIST';
// 缓存数据源list
export const UPDATE_DATASOURCELIST = 'MASTERDATA/MAIN/UPDATE_DATASOURCELIST';
// 保存任务
export const ON_SAVETASK = 'MASTERDATA/MAIN/ON_SAVETASK';
// 更新任务
export const ON_UPDATETASK = 'MASTERDATA/MAIN/ON_UPDATETASK';
// 设置实体的任务类型
export const SET_ENTITYTASKTYPE = 'MASTERDATA/MAIN/SET_ENTITYTASKTYPE';
// 保存任务的流程编排
export const SAVE_TASKARRAY = 'MASTERDATA/MAIN/SAVE_TASKARRAY';
// 打开图形编辑器中的组件编辑窗口
export const OPEN_EDITWINDOW = 'MASTERDATA/MAIN/OPEN_EDITWINDOW';
// 请求任务的流程编排
export const REQ_TASKARRAYLIST = 'MASTERDATA/MAIN/REQ_TASKARRAYLIST';
// 通过任务ID请求任务
export const REQ_TASKBYID = 'MASTERDATA/MAIN/REQ_TASKBYID';
// 缓存任务的流程编排
export const UPDATE_TASKARRAYLIST = 'MASTERDATA/MAIN/UPDATE_TASKARRAYLIST';
// 打开图形编辑器中的组件编辑窗口
export const CLOSE_EDITWINDOW = 'MASTERDATA/MAIN/CLOSE_EDITWINDOW';
// 选择数据源后请求相应的表列表
export const REQUEST_TABLES = 'MASTERDATA/MAIN/REQUEST_TABLES';
// 缓存表list
export const UPDATE_TABLELIST = 'MASTERDATA/MAIN/UPDATE_TABLELIST';
// 请求字段list
export const REQUEST_FIELDS = 'MASTERDATA/MAIN/REQUEST_FIELDS';
// 缓存字段list
export const UPDATE_FIELDLIST = 'MASTERDATA/MAIN/UPDATE_FIELDLIST';
// 缓存当前编辑的组件数据
export const SET_CURRENTEDITCOMPONENTDATA = 'MASTERDATA/MAIN/SET_CURRENTEDITCOMPONENTDATA';
// 改变任务的状态  包括启用、停用等
export const CHANGE_TASKSTATUS = 'MASTERDATA/MAIN/CHANGE_TASKSTATUS';
// 缓存前面所有组件的流字段
export const SET_COMPONENTFLOWFIELDS = 'MASTERDATA/MAIN/SET_COMPONENTFLOWFIELDS';
// 执行sql语句
export const EXCUTE_SQLSENTENCE = 'MASTERDATA/MAIN/EXCUTE_SQLSENTENCE';

//对任务执行日志进行操作的请求
export const REQUEST_HANDLE_TASKEXECUTELOG = 'MASTERDATA/MAIN/REQUEST_HANDLE_TASKEXECUTELOG';
//更新任务执行日志列表
export const UPDATE_TASKEXECUTELOGPAGE = 'MASTERDATA/MAIN/UPDATE_TASKEXECUTELOGPAGE';
//缓存当前组件标题：taskName
export const SET_TASKNAME = 'MASTERDATA/MAIN/SET_TASKNAME';

//缓存SQL字段
export const SET_SQLT_FIELDLIST = 'MASTERDATA/MAIN/SET_SQLT_FIELDLIST';
//缓存SimpleTable字段
export const SET_ST_FIELDLIST = 'MASTERDATA/MAIN/SET_ST_FIELDLIST';
//请求审批数据 过滤数据
export const REQUEST_FILTER_DATA = 'MASTERDATA/MAIN/REQUEST_FILTER_DATA';
//存放审批数据 过滤数据
export const FILTER_DATA_LIST = 'MASTERDATA/MAIN/FILTER_DATA_LIST';
//审批 与 驳回
export const APPROVE_ENTITY_DATA = 'MASTERDATA/MAIN/APPROVE_ENTITY_DATA';
//数据量界面 导出
export const EXPORT_ENTITY_DATA = 'MASTERDATA/MAIN/EXPORT_ENTITY_DATA';
//请求UC矩阵
export const REQUEST_UC = 'MASTERDATA/MAIN/REQUEST_UC';
//UC矩阵请求结果
export const SET_UC = 'MASTERDATA/MAIN/SET_UC';













